# ansible-playbook make-vms-dota.yaml -e 'ansible_python_interpreter=python2'
---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm-2940.dota-lab.iad.redhat.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: redhat1

    - name: Create VMs
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: rhel75
        storage_domain: ssd2-vmstore
        name: "{{ item }}"
        state: running
        instance_type: Small
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.dota-lab.iad.redhat.com"
          user_name: root
          root_password: RedHat1!
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.dota-lab.iad.redhat.com
              - yum -y remove cloud-init
        wait: true
      with_items:
         - vm01
         - vm02
         - vm03

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
