# $ ansible-playbook vm-make-snapshots.yml --ask-vault-pass -e 'vmVars=home.lab/ocp-cns-vars.yml' -e 'snapDescription="Before a big change"'
---
- hosts: localhost
  vars:
    snapState: present
    snapDescription: "changeme"
    vms:
      - vm01
      - vm02
      - vm03

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm-2940.dota-lab.iad.redhat.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: redhat1

    - name: Create snapshots
      ovirt_snapshot:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item.key }}"
        state: "{{ snapState }}"
        description: "{{ snapDescription }}"
        wait: false
      with_dict: "{{ vms }}" # See home.lab/ocp-cns-vars.yml

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
