---
- hosts: all
  name: Scan System with OpenSCAP for Known Vulnerabilities

  tasks:
    - name: Install openscap
      yum: name=openscap-scanner state=latest
      when: ansible_distribution == "RedHat"

    - name: Creating /opt/security-scan/
      file:
        path: "/opt/security-scan"
        state: "directory"
        owner: root
        group: root
        mode: 0700

    - name: Mount NFS from rhclient4 to store html reports
      mount:
        path: /opt/security-scan
        src: rhclient4.dota-lab.iad.redhat.com:/data/vulnerability-scan-reports
        state: mounted
        fstype: nfs

    - name: Download Red Hat Security Advisory Datastream file | com.redhat.rhsa-RHEL7.ds.xml
      get_url:
        url: "https://www.redhat.com/security/data/metrics/ds/com.redhat.rhsa-RHEL7.ds.xml"
        dest: "/opt/security-scan/com.redhat.rhsa-RHEL7.ds.xml"
        mode: "0600"
      when: ansible_distribution_major_version == "7"

    - name: Running Red Hat Security Advisory scan | firefox /opt/security-scan/report.html to review
      command: "oscap xccdf eval --results /opt/security-scan/results.xml --report /opt/security-scan/report.html /opt/security-scan/com.redhat.rhsa-RHEL7.ds.xml"
      ignore_errors: yes
      when: ansible_distribution_major_version == "7"

    - name: Unmount NFS from rhclient4 to store html reports
      mount:
        path: /opt/security-scan
        state: absent
